[package]
name = "tilemap-flowfields-native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = { version = "0.11", features = ["serde"] }
rayon = "1.5.3"
serde = { version = "1.0.146", features = ["derive"] }
