on:
  push: 
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            bin: native/target/libflowfield_tilemap_native.dll
          - target: x86_64-unknown-linux-musl
            bin: native/target/libflowfield_tilemap_native.so
          - target: x86_64-apple-darwin
            bin: native/target/libflowfield_tilemap_native.so
    steps: 
      - name: checkout
        uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - name: build
        uses: actions-rs/cargo@v1
        id: build
        with:
          command: build
          use-cross: true
          args: --release --target ${{ matrix.target }}
