on:
  push: 
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            bin: native/target/libflowfield_tilemap_native.dll
          - target: x86_64-unknown-linux-musl
            bin: native/target/libflowfield_tilemap_native.so
          - target: x86_64-apple-darwin
            bin: native/target/libflowfield_tilemap_native.so
    steps: 
      - name: checkout
        uses: actions/checkout@master
      - name: compile
        uses: rust-build/rust-build.action@v1.3.2
        id: compile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          UPLOAD_MODE: none
          SRC_DIR: "native"
          NAME: ${{ matrix.name }}
          EXTRA-FILES: ${{ matrix.bin }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
