on:
  push: 
    branches: "main"

defaults:
 run:
  working-directory: ./native

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
          - target: x86_64-unknown-linux-musl
          - target: x86_64-apple-darwin
    steps: 
      - name: checkout
        uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}  
      - name: build
        uses: actions-rs/cargo@v1
        id: build
        with:
          command: build
          use-cross: true
          args: --release --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v3
        with:
          path: |
            **/*.dll
            **/*.so
